# Generated by Django 6.1.1 on 2026-09-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('cargo', models.CharField(max_length=120, verbose_name='Cargo / Rol')),
                ('bio', models.TextField(verbose_name='Biografía')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='coordinadores/', verbose_name='Foto')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Coordinador',
                'verbose_name_plural': 'Coordinadores',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/', verbose_name='Imagen')),
                ('enlace', models.URLField(blank=True, verbose_name='Enlace externo')),
                ('publicado', models.BooleanField(default=True, verbose_name='¿Publicado?')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='GaleriaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('imagen', models.ImageField(upload_to='galeria/', verbose_name='Imagen')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('publicado', models.BooleanField(default=True, verbose_name='¿Publicado?')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Elemento de galería',
                'verbose_name_plural': 'Galería',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('descripcion_corta', models.TextField(verbose_name='Descripción corta')),
                ('descripcion_completa', models.TextField(blank=True, verbose_name='Descripción completa')),
                ('icono', models.CharField(blank=True, max_length=50, verbose_name='Clase de icono (opcional)')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='programas/', verbose_name='Imagen')),
                ('publicado', models.BooleanField(default=True, verbose_name='¿Publicado?')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo / Empresa')),
                ('texto', models.TextField(verbose_name='Testimonio')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='testimonios/', verbose_name='Foto')),
                ('publicado', models.BooleanField(default=True, verbose_name='¿Publicado?')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
